# Example Development Build
version: '2'
services:
    ghost:
        image: zzrot/alpine-ghost
        environment:
          DEV_DOMAIN: http://192.168.99.100:2368
        volumes:
          - ./your/contentfolder:/var/lib/ghost/
        ports:
            - 2368:2368


# Example Production Build
version: '2'
services:
    ghost:
        image: zzrot/alpine-ghost
        environment:
          PROD_DOMAIN: http://yourwebsiteurl.com/blog
          NODE_ENV: production
        volumes:
          - ./your/contentfolder:/var/lib/ghost/
        ports:
            - 2368:2368
